// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuNgItPFaC5y5kvyz-7CS_naPIx8tt1Mw',
    appId: '1:967097017943:web:94cc86939280640177e512',
    messagingSenderId: '967097017943',
    projectId: 'shopsphere-ai-2477a',
    authDomain: 'shopsphere-ai-2477a.firebaseapp.com',
    storageBucket: 'shopsphere-ai-2477a.firebasestorage.app',
    measurementId: 'G-42V4BBWYWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgQI1Jtd58uEyBz2VDaYvDiHs3NsLl_yM',
    appId: '1:967097017943:android:cb06f963d6ad85ed77e512',
    messagingSenderId: '967097017943',
    projectId: 'shopsphere-ai-2477a',
    storageBucket: 'shopsphere-ai-2477a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPfZ1a5nRmLjulBnlak-CgnGN9JMH7ips',
    appId: '1:967097017943:ios:9e79aa650e9acf4277e512',
    messagingSenderId: '967097017943',
    projectId: 'shopsphere-ai-2477a',
    storageBucket: 'shopsphere-ai-2477a.firebasestorage.app',
    iosClientId: '967097017943-473fhsvpcqhijp1886010jvbjl2cmkj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPfZ1a5nRmLjulBnlak-CgnGN9JMH7ips',
    appId: '1:967097017943:ios:9e79aa650e9acf4277e512',
    messagingSenderId: '967097017943',
    projectId: 'shopsphere-ai-2477a',
    storageBucket: 'shopsphere-ai-2477a.firebasestorage.app',
    iosClientId: '967097017943-473fhsvpcqhijp1886010jvbjl2cmkj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuNgItPFaC5y5kvyz-7CS_naPIx8tt1Mw',
    appId: '1:967097017943:web:7423597eabad071e77e512',
    messagingSenderId: '967097017943',
    projectId: 'shopsphere-ai-2477a',
    authDomain: 'shopsphere-ai-2477a.firebaseapp.com',
    storageBucket: 'shopsphere-ai-2477a.firebasestorage.app',
    measurementId: 'G-40SWSBPYFX',
  );
}
